language: python
python:
  - "3.7"
# command to install dependencies

install:
  - "pip install -r requirements.txt"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "source env.sh"

# command to run tests

script:
  - pytest Python_Testing_Scripts

